---
title: "TurbSS Processing"
author: "John Kemper"
date: "10/17/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(googledrive)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(xts)
library(ggthemes)
library(readxl)
library(tools)
library(fs)
library(stringr)
library(purrr)
library(raster)
library(dygraphs)

```


##Data download from Google Drive
```{r}
###Specify the drive using the drive URL
turb_drive <- drive_get("https://drive.google.com/drive/u/1/folders/13K-gaXcBkCkLl1TTBw2tVQCjwsAUvSIW/")

###List files on drive
files <- drive_ls(turb_drive)

###Extract only the data files
excelFiles <- files %>%
  filter(str_detect(name, ".xlsx")) 

###Function to download the files from Drive and put them in a data folder
turb_download <- function(x, y) {
  drive_download(as_id(x), overwrite = TRUE)
  
  file_move(y, "C:/Users/jkemper/Documents/UrbanSediment/DRSediment/data")
  
  
}


###Download and store the files
map2(excelFiles$id, excelFiles$name, turb_download)






```


###Get file parameters from file folders
```{r}

###Get data file names
turb_files <- list.files("data")


#file.remove("data/~$DR4.xlsx")

###Get station names
turb_file_names <- turb_files %>% str_split(., "\\.") %>%
  unlist() %>%
  str_subset(., "DR")

###Extract all sheets
#sheets <- excel_sheets(paste0("./data/", turb_files[2])) %>%
  #str_extract("201.$") %>%
  #.[!is.na(.)]


```


```{r}
##File manipulation


for(i in 1:length(turb_files)) {
  
  sheet_extractor <- function(strng){
    
  sheets <- excel_sheets(paste0("./data/", strng)) %>%
    str_extract("201.$") %>%
    .[!is.na(.)]
  
  print(sheets)
  

  }
  
  file_name_extractor <- function(srg) {
    
    turb_file_names <- srg %>% str_split(., "\\.") %>%
      unlist() %>%
      str_subset(., "DR")
    
  }
  
  print(turb_files[i])
  
  sheets <- sheet_extractor(turb_files[i])
  
  file_name_extractor(turb_files[i])
  
  tmp <- map(sheets, read_xlsx, path = (paste0("./data/", turb_files[i]))) %>%
    bind_rows() %>%
    as_tibble() %>%
    dplyr::select(1:17)
    
  
  write_csv(tmp, paste0("data/", turb_file_names[i], "_allyears.csv"))
  
}


```



###Select storms
```{r}
setwd("C:/Users/jkemper/Documents/UrbanSediment/DRSediment")

DR5 <- read_csv("data/DR5_allyears.csv") %>%  
  rename_all(~str_replace_all(., " ", "_")) %>%
  rename_all(~str_remove_all(., "[\\( \\)<>-]")) %>%
  rename_all(~str_remove_all(., "__")) %>%
  rename_all(~str_remove_all(., "[/*^=]")) %>%
  rename(datetime = 1)

###Add columns that calculate the change in discharge over 5 timesteps 
###This is important for picking storms
DR5_turb_test <- DR5 %>%
  dplyr::select(1:12) %>%
  filter(!is.na(datetime)) %>%
  slice(1:10000) %>%
  rename(Discharge_LperS = 3) %>%
  filter(!is.na(Discharge_cfs)) %>%
  mutate(delta_turb_lag = abs(Discharge_cfs - lag(Discharge_cfs))) %>%
  mutate(delta_turb_lag = replace_na(delta_turb_lag, 0)) %>%
  mutate(delta_turb_lag2 = abs(Discharge_cfs - lag(Discharge_cfs, n = 2))) %>%
  mutate(delta_turb_lag2 = replace_na(delta_turb_lag2, 0)) %>%
  mutate(delta_turb_lead = abs(Discharge_cfs - lead(Discharge_cfs))) %>%
  mutate(delta_turb_lead = replace_na(delta_turb_lead, 0)) %>%
  mutate(delta_turb_lead2 = abs(Discharge_cfs - lead(Discharge_cfs, n = 2))) %>%
  mutate(delta_turb_lead2 = replace_na(delta_turb_lead2, 0))


names(DR5_turb_test)


DR5_plot <- DR5_turb_test %>%
  xts(., select(-datetime),
      order.by = .$datetime) %>%
  dygraph(.)

DR5_plot

DR5_ts <- DR5_turb_test %>%
  xts(., select(-datetime),
      order.by = .$datetime) 


# storm_finder <- function(lst) {
  
  # x <- lst[[1]][2]
  
  # if(lst[[1]][i,2] > lst[[1]][(i+1),2])
    
    
  

# }
  
###Function that identifies storms based on the change in discharge over 5 timesteps
###If that change > 0.3, then it labels that row with a 1 (indicating a storm)
###If it is less than 0.3, then it lables that row with a 0 (indicating no storm)
storm_picker <- function(df) {
  
  w <- df$delta_turb_lag
  x <- df$delta_turb_lead
  y <- df$delta_turb_lag2
  z <- df$delta_turb_lead2
  
  ifelse((w > 0.3 | x > 0.3 | y > 0.3 | z > 0.3), 1, 0)
  

}

View(DR5_turb_test)

###Detect the storms
###Code indicates whether there is a storm present
###Transform code to logical to make it more sensible to a reader
###line that begins mutate(Group) uses the difference function to detect when there is a change in 
###the isStorm condition (i.e. a change from FALSE to TRUE or vice versa)
###and then uses cumsum to add 1 to the value every time that change occurs
###So what we get is a numerical storm label, i.e. each row in the first storm has 2 in the Group column
###the second storm a 4, and so on
DR5_storms <- DR5_turb_test %>%
  mutate(code = storm_picker(.)) %>%
  mutate(Date = date(datetime)) %>%
  mutate(isStorm = (as.logical(code))) %>%
  mutate(Group = cumsum(c(1,diff(isStorm) != 0))) %>%
  mutate(Storm = ifelse(((Group/2)%%1) != 0, 0, Group/2)) %>%
  dplyr::select(-code) %>%
  filter(isStorm == TRUE) 

```

```{r}
###Nest each storm within a list of storms
DR5_storms_nest <- DR5_storms %>%
  nest(-Storm)

###Calculate some storm stats
DR5_storms_stats <- DR5_storms %>%
  group_by(Storm) %>%
  summarise(MaxQ = max(Discharge_mmd),
            MeanQ = mean(Discharge_mmd),
            MaxSSC = max(Suspended_sediment_concentration_mgL_y__2.4x0.98),
            MeanSSC = mean(Suspended_sediment_concentration_mgL_y__2.4x0.98),
            dQ_Q = ((max(Discharge_mmd) - Discharge_mmd[1])/Discharge_mmd[1]),
            Yield = sum(Suspended_sediment_load_kg_per_30_or_5_minutes),
            x = (datetime[1] - datetime[2]))

View(DR5_storms_stats)

###Make CQ plots
plot_maker <- function(df) {
  
  df %>%
    mutate(ticker = row_number(datetime)) %>%
    ggplot(aes(x = Discharge_cfs, y = Turbidity_FNU_raw, color = ticker)) +
    geom_point(size = 5, shape = 1, stroke = 2) +
    geom_path() +
    theme_few() +
    scale_color_gradientn(colours = viridis::plasma(10))
  
  name <- date(df$datetime[1])
  
  ggsave(paste0(name,".png"), path = "C:/Users/jkemper/Documents/UrbanSediment/DR5_CQ_plots")
  
}

zz <- DR5_storms_nest %>%
  mutate(MaxQ = map(data, ~max(.x$Discharge_cfs))) %>%
  slice(1:3)


map(zz$data, ~plot_maker(.x))




```

